version: "2.4"
services:
    access-point:
        image: beroset/dlms-access-point
        entrypoint: 
            - /tmp/docker-entrypoint.sh
            - "access-point"
            - 2001:3200:3201::100:100 
            - "8888"
        expose:
            - "4059/tcp"
        ports:
            # this port is used to get network stats and control tc qdisc netem
            - "8888:8888"
        networks:
            meternet:
            backhaul:
              ipv6_address: 2001:3200:3201::100:101
        cap_add:
            - NET_ADMIN
        sysctls:
            net.ipv6.conf.all.disable_ipv6: 0
            net.ipv6.conf.all.forwarding: 1

    meter:
        image: beroset/dlms-access-point
        entrypoint: 
            - /tmp/docker-entrypoint.sh
            - "meter"
            - 2001:3200:3201::100:100 
            - "8888"
        expose:
            - "4059/tcp"
        networks:
            - meternet
        cap_add:
            - NET_ADMIN
        sysctls:
            net.ipv6.conf.all.disable_ipv6: 0

    hes:
        image: beroset/dlms-access-point
        entrypoint: 
            - /tmp/HESsim
            - 2001:3200:3201::100:101
        expose:
            - "4059/tcp"
        ports:
            - "4060:4060"
        networks:
            backhaul:
              ipv6_address: 2001:3200:3201::100:100
        sysctls:
            net.ipv6.conf.all.disable_ipv6: 0

    dashboard:
        image: beroset/dlms-access-point-dashboard
        ports:
            - "8081:80"
        networks:
            - meternet
        sysctls:
            net.ipv6.conf.all.disable_ipv6: 0

    docs:
        image: beroset/dlms-access-point-docs
        ports:
            - "8080:80"
        networks:
            - docnet

networks:
    docnet:
    backhaul:
        enable_ipv6: true
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 2001:3200:3201::/64
    meternet:
        enable_ipv6: true
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 2001:3200:3200::/64

