version: "2.4"
services:
    meter:
        build:
            args:
                - projectsourcename=dlms-access-point-1.0.0-Source
            context: .
            target: demo
        entrypoint: 
            - /tmp/Metersim 
        expose:
            - "4059/tcp"
        networks:
            - meternet
        sysctls:
            net.ipv6.conf.all.disable_ipv6: 0


    hes:
        image: demo
        entrypoint: 
            - /tmp/HESsim
            - dlms-access-point-meter1
            - dlms-access-point-meter2
            - dlms-access-point-meter3
        networks:
            - meternet
        sysctls:
            net.ipv6.conf.all.disable_ipv6: 0

    docs:
        build:
            args:
                - projectsourcename=dlms-access-point-1.0.0-Source
            context: .
            target: docserver
        ports:
                - "8080:80"
        networks:
            - docnet

networks:
    docnet:
    meternet:
        enable_ipv6: true
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 2001:3200:3200::/64

