version: "2.4"
services:
    dlms-access-point-meter1:
        build:
            args:
                - projectsourcename=dlms-access-point-1.0.0-Source
            context: .
            target: demo
        entrypoint: 
            - /tmp/Metersim 
            - "M1001"
        expose:
            - "4059/tcp"
        networks:
            meternet:
        sysctls:
          net.ipv6.conf.all.disable_ipv6: 0


    dlms-access-point-meter2:
        build:
            args:
                - projectsourcename=dlms-access-point-1.0.0-Source
            context: .
            target: demo
        entrypoint: 
            - /tmp/Metersim 
            - "M1002"
        expose:
            - "4059/tcp"
        networks:
            meternet:
        sysctls:
          net.ipv6.conf.all.disable_ipv6: 0

    dlms-access-point-docs:
        build:
            args:
                - projectsourcename=dlms-access-point-1.0.0-Source
            context: .
            target: docserver
        ports:
                - "8080:80"
        networks:
            - docnet

    dlms-access-point-hes:
        build:
            args:
                - projectsourcename=dlms-access-point-1.0.0-Source
            context: .
            target: demo
        entrypoint: 
            - /tmp/HESsim
            - "8888"
            - dlms-access-point-meter1
            - dlms-access-point-meter2
        expose:
            - "8888/tcp"
        networks:
            hesnet:
            meternet:
        sysctls:
          net.ipv6.conf.all.disable_ipv6: 0

    dlms-access-point-cis:
        build:
            args:
                - projectsourcename=dlms-access-point-1.0.0-Source
            context: .
            target: demo
        entrypoint: 
            - /tmp/CISsim
            - "http://dlms-access-point-hes:8888"
            - "http://dlms-access-point-cis"
        depends_on:
            - dlms-access-point-hes
        networks:
            - hesnet
        sysctls:
          net.ipv6.conf.all.disable_ipv6: 1

networks:
    docnet:
    hesnet:
    meternet:
        enable_ipv6: true
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 2001:3200:3200::/64

